version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=cakephp
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./scripts:/scripts  

  php-apache:
    container_name: ck4php-apache
    build:
      context: .
      dockerfile: Dockerfile
    user: "1001:1001"
    ports:
      - "80:80"
    volumes:
      #- /opt/sites/:/var/www/html/
      - /opt/sites/form-podcast/www/:/var/www/html/

networks:
  default:
    external:
      name: internal
